### PR TITLE
Added Polish Translation

### PR DESCRIPTION
**Pull request by 6vz**

### CODE REVIEW

**Comment by 6vz** [comment]
https://user-images.githubusercontent.com/78034446/119776085-c8671b80-bec4-11eb-8407-0099feb7aabd.mp4

Waiting for Merge... Day 4 or 5

**Comment by AlexFlipnote** [comment]
```py
Traceback (most recent call last):
  File "_validate_languages.py", line 32, in <module>
    raise KeyError(f"You can't have 2 words inside a string ({file}) | {all_words_failed}")
KeyError: "You can't have 2 words inside a string (pl.json) | różnią się, w dół, na sucho, w trakcie, z przodu, zdarzyło się, po prostu, uczyć się, w lewo, na żywo, o nie, na zewnątrz, w prawo, to samo, po drugie, wydaje się, z boku, do góry, w kierunku, w górę, podczas gdy"
```

**Comment by 6vz** [comment]
Should be good now @AlexFlipnote

**Comment by AlexFlipnote** [comment]
From the codebase:
```sh
codespace ➜ /workspaces/TypingTest (pr/6vz/16) $ python _validate_languages.py 
All checks passed :)
```

**Pull request merged**
